baseURL = "http://example.org/"
theme = "hugo-theme-codex"
languageCode = "en-us"
title = "Leisure experiences of the video game developers"
enableEmoji = true
copyright = "© 2020−2021. Cultural participation of video game developers"

[params]
  author = "Raman Voranau"
  description = "A simple monospaced resume theme for Hugo."
  favicon = "favicon.ico"
  [params.footer]
    text = "By Raman Voranau"
    url = "https://github.com/voranau"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Researcher"
    url = "/researcher"
    weight = 4
  [[menu.main]]
    name = "Team"
    url = "/team"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files